HOST:
  URL: ''
  SPACE_NAME: ''

API_KEY:
  VALUE: ''

PERSON_HOURS_PER_DAY: 7.5
PROCESSING_PROJECT_KEY:
  - [ProjectKey]

PROCESSING_TERM:
  START_DATE: '2017-09-01'
  END_DATE: '2017-09-30'

PROCESSING_ISSUE_TYPE_NAME: 'タスク'
PROCESSING_UPDATE_WIKI:
  IS_UPDATE: false
  WIKI_ID: ''
