API_KEY:
  GLOBAL: ''
  IP: ''

WIKI_SPACE: ''

PROCESSING_PROJECT_KEY:
  - [PROJECT_KEY]

PROCESSING_DATETIME: ''

PROCESSING_ISSUE_TYPE_NAME: 'タスク'

PROCESSING_UPDATE_WIKI:
  SUMMARY_WIKI_ID: 
  DETAIL_WIKI_ID: 
