API_KEY:
  GLOBAL: ''

WIKI_SPACE: ''

PROCESSING_PROJECT_KEY:
  - [PROJECT_KEY]

PROCESSING_DATETIME: ''

PROCESSING_ISSUE_TYPE_NAME: 'タスク'

PROCESSING_UPDATE_WIKI:
  IS_UPDATE: true
  SUMMARY_WIKI_ID: 
  DETAIL_WIKI_ID: 

ALERT:
  IS_ENABLE: false
  CHATWORK_API_TOKEN: 
  CHATWORK_ROOM_ID: 
  CHATWORK_TO_ACCOUNT_LIST: 
    - ID: ""
      NAME: ""